name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Channel to promote from
        options:
          - edge -> beta
          - beta -> candidate
          - candidate -> stable
      track-name:
        type: choice
        description: Name of the charmhub track to publish
        options:
          - 1.4
          - latest


jobs:
  promote:
    name: Promote Charm
    uses: canonical/sdcore-github-workflows/.github/workflows/promote.yaml@v0.0.2
    with:
      promotion: ${{ github.event.inputs.promotion }}
      track-name: ${{ github.event.inputs.track-name }}

    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
